### ISSUE TITLE
TypeError: this.ssh2Client is not a constructor

### ISSUE THREAD

**Issue by cchretien** [cmp-202/ssh2shell#87]
Using the latest version of ssh2shell 1.9.6 causes the following exception
```
TypeError: this.ssh2Client is not a constructor
    at SSH2Shell._connect (C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:823:25)
    at C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:4:59
    at SSH2Shell._initiate (C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:659:16)
    at SSH2Shell._initiate (C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:4:59)
    at SSH2Shell._nextPrimaryHost (C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:423:21)
    at SSH2Shell._nextPrimaryHost (C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:4:59)
    at SSH2Shell.connect (C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:818:47)
    at SSH2Shell.connect (C:\workspace\myproj\node_modules\ssh2shell\lib\ssh2shell.js:4:59)
    ....
    ...
```
Looks like bumping ssh2 to the new major version caused a break.

https://github.com/cmp-202/ssh2shell/commit/c7c2372c3f282e6ee538e94cd5f2eef12d0fee4f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

I looked at ssh2 since it's been a while and noticed that all the client examples have changed as it relates to the requires.

**Comment by cmp-202** [comment]
That was incredibly lazy of me, sorry.
I will get onto that now.

Andrew

**Comment by cmp-202** [comment]
That's fixed.

Andrew

**Comment by cchretien** [comment]
Thanks Andrew. Noticed the fix. 

Given that you bumped the node version to 14 that kind of implies a major bump in the project release. This would break me again as I usually just pin the major release and I'm not on nodejs 14 yet. You might want consider bumping the project to a major version and remove 1.9.6-7 to avoid breaking others.

For now, I've pinned to 1.9.5 so I'm technically alright.

Thanks for your help

**Comment by cmp-202** [comment]
I reverted node version back to >=4.5.0
